CREATE SCHEMA IF NOT EXISTS user_service_schema;
GRANT ALL ON SCHEMA user_service_schema TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA user_service_schema GRANT ALL ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA user_service_schema GRANT ALL ON SEQUENCES TO app;
